### ISSUE TITLE
test "Getting started" on ubuntu. compile failed

### ISSUE THREAD

**Issue by zfyseu** [TresysTechnology/refpolicy#35]
Hello!
I want to follow the instruction of  "Getting started"  on ubuntu. However it seems failed.
when i do "semodule -i myapp.pp"
it returns with the error "Could not access sandbox base file /etc/selinux/ubuntu/modules/tmp/base.pp. (No such file or directory).
semodule:  Failed!"

How to solve the problem?
Thank you

**Comment by pebenito** [comment]
Is your system fully configured, e.g. you did `sudo apt-get install selinux` and rebooted, etc. and everything is working?

On a side note, I suggest using `#selinux` on `irc.freenode.net` if you'd like quicker response.

**Comment by zfyseu** [comment]
Thanks you, pebenito!
I have done "sudo apt-get install selinux" and "reboot".
Everything is working except that "Makefile.example" not work well.
And I do "apt-get install libselinux1-dev" and "make -f /usr/share/selinux/devel/Makefile"
it did work. AND is it OK?

**Comment by zfyseu** [comment]
And I do the same thing in fedora. it succeed.

**Comment by pebenito** [comment]
Yes, you should use the `make -f /usr/share/selinux/devel/Makefile` so the build process uses the policy headers that come with your distribution's policy, as they may be slightly different from what is available in refpolicy. That is ok.
