### ISSUE TITLE
Fails over modules.conf

### ISSUE THREAD

**Issue by Melab** [TresysTechnology/refpolicy#36]
Running `make` in the root of the tree returns `Rules.modular:145: *** No enabled modules! modules.conf may need to be generated by using "make conf".  Stop.`. Running `make conf` returns `make: *** No rule to make target `policy/modules/contrib/metadata.xml', needed by `tmp/admin.xml'.  Stop.
`. What is wrong?

**Comment by pebenito** [comment]
If you check out the refpolicy source tree, you need to either provide a `modules.conf` or generate one using `make conf` before you can build the policy.
