### ISSUE TITLE
'make policy' complains about missing /seusers directory on Debian 8

### ISSUE THREAD

**Issue by IVXCVI** [TresysTechnology/refpolicy#95]
`make policy` returns:
```
make: *** No rule to make target '/seusers', needed by 'tmp/seusers'.  Stop.
```
All dependencies listed in `INSTALL` seem to be met. I prefaced the `make policy` command with `make config`, and it seemed to pass without issue.

Any help would be really great.

**Comment by IVXCVI** [comment]
[Here I have attached the output of `make clean && make -d policy`](https://gist.githubusercontent.com/IVXCVI/ba942505ac2fa9356038a3665b4533c3/raw/2f0afc16276bc8effaa73f74244fa13a1b280cbd/refpolicy%2520-%2520make%2520clean%2520&&%2520make%2520-d%2520policy).

**Comment by fishilico** [comment]
Thanks for the detailed output. Could you please check that there is no space after TYPE=mcs in your build.conf? This would explain the error you are experiencing.

My understanding of what is happening is the following:

- Target ``tmp/seusers`` requires ``$(seusers)`` (https://github.com/TresysTechnology/refpolicy/blob/RELEASE_2_20170204/Rules.modular#L101)
- This variable is defined as ``$(appconf)/seusers``, with ``appconf := config/appconfig-$(TYPE)`` (https://github.com/TresysTechnology/refpolicy/blob/RELEASE_2_20170204/Makefile#L248)
- ``$(TYPE)`` is loaded from build.conf
- Your output suggests that ``$(seusers)`` is expanded to ``config/appconfig-mcs /seusers`` with a space or an other blank character.

**Comment by IVXCVI** [comment]
Good catch m8! I wouldn't have noticed that by just looking at the output. Thanks! Now on to tackle the next step.
